Spring:
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: ICT
        generate-ddl: true
        show-sql: true
        servlet:
          multipart:
            enabled: true
            max-file-size: 5MB
            max-request-size: 5MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/affiliatenew
    username: root
    password: 12345678

app:
  token:
    secret: affiliate2022
    issuer: affiliate